global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prome-local'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'question5'
    static_configs:
      - targets: ['host.docker.internal:8000']